name: Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-and-build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: 'stable'
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Lint
        if: matrix.platform == 'ubuntu-latest'
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build
